# Mirrored at templates/ci/.github/workflows/ci.yaml — keep in sync.
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  checks:
    permissions:
      checks: write
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: nix flake check
        run: nix -v flake check --show-trace --impure --accept-flake-config

      - name: cargo build
        run: nix develop --impure --accept-flake-config -c cargo build --all-targets --locked

      - name: cargo test
        run: nix develop --impure --accept-flake-config -c cargo test --all-targets --locked

      - name: cargo clippy
        run: nix develop --impure --accept-flake-config -c cargo clippy --all-targets --locked -- -D warnings
